# Packing for three months in Southeast Asia

So, soon I'll be leaving to Singapore, Malasya, Indonesia, Hong Kong and Vietnam for a duration of three monts. Since it is the first "long" trip I will be doing, I wondered what and how much stuff should I pack into my luggage.

Initially I thought of using a small and handy suitcase, but quickly discarded the idea, as I would be sacrifying flexibility, versatility and comfort of using a backpack. 

So, what to pack? the main goal of the trip is to wander around with no fixed course, looking for cool spots, beautiful beaches and nice trekkings in the mountains, so I'd want it to be as light as possible and stick to the bare minimum.

I made a list of items I've chosen to carry, divided by topic:

## Clothing

* 3 t-shirts
* 2 sleeveless t-shirts
* 1 shirt: I've chosen a thin tissue and hawaiian-like shirt so I can use them when walk around the city at night and I want to be more "presentable" than with a simple t-shirt.
* 1 long trouser
* 2 shorts
* 1 swimsuit
* 3 pairs of socks / 3 pairs of underwear
* 1 pair of boots
* 1 pair of short comfy shoes
* 1 pair of slippers
* 1 cap
* 1 oilskin
* 1 microfiber towel


## Tech

* laptop + charger + case
* phone + case
* universal socket adapter


## Toilet

* toothbrush
* deodorant
* cream(s)
* laundry kit


## Medical

* anti-mosquitoes bracelet & spray
* sunscreen
* antiacid & Paracetamol
* antimalaria pills


## Misc

* reusable bottle
* lock(s)
* light camping bag
* Spork (spook-fork)
* earplugs
* photocopied documentation



That's it! I hope I won't miss anything important, I guess it is as light as it could be, wish me luck!
